# Generated by Django 6.0.3 on 2026-03-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('', 'Aucun'), ('admin', 'Admin'), ('moderator', 'Modérateur'), ('support', 'Support'), ('ops', 'Ops')], default='', max_length=20, verbose_name='rôle admin interne'),
        ),
    ]
