# Generated by Django 6.0.3 on 2026-03-22 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('start_at', models.DateTimeField(verbose_name='début')),
                ('end_at', models.DateTimeField(verbose_name='fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='professionals.professionalprofile')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='services.massageservice')),
            ],
            options={
                'verbose_name': 'créneau disponible',
                'verbose_name_plural': 'créneaux disponibles',
                'ordering': ('start_at',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('client_first_name', models.CharField(max_length=120, verbose_name='prénom')),
                ('client_last_name', models.CharField(max_length=120, verbose_name='nom')),
                ('client_email', models.EmailField(max_length=254, verbose_name='email')),
                ('client_phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('client_note', models.TextField(blank=True, verbose_name='note client')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('canceled', 'Annulée')], default='pending', max_length=20, verbose_name='statut')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='professionals.professionalprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.massageservice')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='bookings.availabilityslot')),
            ],
            options={
                'verbose_name': 'réservation',
                'verbose_name_plural': 'réservations',
                'ordering': ('-created_at',),
            },
        ),
    ]
