# Generated by Django 6.0.3 on 2026-03-22 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('professionals', '0002_professionalprofile_cover_photo_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='label',
            field=models.CharField(blank=True, max_length=120, verbose_name='libellé'),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='slot_type',
            field=models.CharField(choices=[('open', 'Créneau réservable'), ('blocked', 'Plage bloquée')], default='open', max_length=20, verbose_name='type de créneau'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.availabilityslot'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['professional', 'start_at'], name='bookings_av_profess_6453c3_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['professional', 'slot_type', 'is_active'], name='bookings_av_profess_e71a3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'confirmed'))), fields=('slot',), name='unique_active_booking_per_slot'),
        ),
    ]
