# Generated by Django 6.0.3 on 2026-03-23 23:36

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_availabilityslot_label_availabilityslot_slot_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_due_now_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='montant demandé maintenant'),
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_received_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='montant reçu'),
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_refunded_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='montant remboursé'),
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_remaining_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='reste à régler'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_notice_hours',
            field=models.PositiveIntegerField(default=24, verbose_name="annulation sans frais jusqu'à"),
        ),
        migrations.AddField(
            model_name='booking',
            name='keep_payment_after_deadline',
            field=models.BooleanField(default=True, verbose_name='conserver le règlement après le délai'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_message',
            field=models.CharField(blank=True, max_length=220, verbose_name='message affiché au client'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('none', 'Sans paiement à la réservation'), ('deposit', 'Avec acompte'), ('full', 'Avec paiement total')], default='none', max_length=20, verbose_name='mode de règlement appliqué'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('none', 'Aucun paiement demandé'), ('deposit_required', 'Acompte attendu'), ('deposit_paid', 'Acompte reçu'), ('fully_paid', 'Paiement reçu'), ('refunded', 'Remboursé'), ('canceled', 'Annulé')], default='none', max_length=20, verbose_name='statut de règlement'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='prix total'),
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('kind', models.CharField(choices=[('deposit', 'Acompte'), ('full', 'Paiement total'), ('refund', 'Remboursement')], max_length=20, verbose_name='type de règlement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('succeeded', 'Réussi'), ('refunded', 'Remboursé'), ('canceled', 'Annulé')], default='pending', max_length=20, verbose_name='statut')),
                ('provider', models.CharField(choices=[('internal_demo', 'Connecteur interne de démonstration'), ('stripe', 'Stripe')], default='internal_demo', max_length=30, verbose_name='prestataire')),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='montant')),
                ('provider_reference', models.CharField(blank=True, max_length=120, verbose_name='référence prestataire')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'règlement de réservation',
                'verbose_name_plural': 'règlements de réservation',
                'ordering': ('-created_at',),
            },
        ),
    ]
