# Generated by Django 6.0.3 on 2026-03-24 07:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def migrate_payment_statuses(apps, schema_editor):
    Booking = apps.get_model("bookings", "Booking")
    BookingPayment = apps.get_model("bookings", "BookingPayment")

    booking_status_map = {
        "none": "none_required",
        "deposit_required": "deposit_required",
        "deposit_paid": "payment_pending",
        "fully_paid": "payment_pending",
        "refunded": "refunded",
        "canceled": "canceled",
    }

    for booking in Booking.objects.all():
        previous = booking.payment_status
        booking.payment_status = booking_status_map.get(previous, "none_required")
        if previous in {"deposit_paid", "fully_paid"}:
            booking.amount_received_eur = Decimal("0.00")
        booking.save(update_fields=["payment_status", "amount_received_eur", "updated_at"])

    payment_provider_map = {
        "internal_demo": "system",
        "stripe": "stripe_connect",
    }
    payment_status_map = {
        "succeeded": "captured",
        "pending": "pending",
        "refunded": "refunded",
        "canceled": "canceled",
    }
    for payment in BookingPayment.objects.all():
        payment.provider = payment_provider_map.get(payment.provider, payment.provider)
        payment.status = payment_status_map.get(payment.status, payment.status)
        payment.save(update_fields=["provider", "status", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_amount_due_now_eur_and_more'),
        ('professionals', '0006_professionalpaymentaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='auto_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='validation automatique le'),
        ),
        migrations.AddField(
            model_name='booking',
            name='canceled_by_role',
            field=models.CharField(choices=[('client', 'Client'), ('practitioner', 'Praticien'), ('platform', 'Plateforme'), ('system', 'Système')], default='system', max_length=20, verbose_name='annulé par'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=220, verbose_name="raison d'annulation"),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='client arrivé le'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='prestation validée par le client le'),
        ),
        migrations.AddField(
            model_name='booking',
            name='fulfillment_status',
            field=models.CharField(choices=[('scheduled', 'Planifié'), ('client_arrived', 'Client arrivé'), ('in_progress', 'Prestation commencée'), ('completed_by_practitioner', 'Terminée par le praticien'), ('completed_validated_by_client', 'Validée par le client'), ('disputed', 'Signalée'), ('auto_completed', 'Validée automatiquement')], default='scheduled', max_length=40, verbose_name='statut de prestation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_authorized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='autorisation de règlement reçue le'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_captured_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='règlement capturé le'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_channel',
            field=models.CharField(choices=[('none', 'Non précisé'), ('platform', 'Plateforme'), ('cash', 'Espèces'), ('bank_transfer', 'Virement'), ('card_reader', 'Terminal'), ('other', 'Autre')], default='none', max_length=20, verbose_name="canal d'encaissement"),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_collection_method',
            field=models.CharField(choices=[('none', 'Aucun règlement à la réservation'), ('platform', 'Plateforme'), ('on_site', 'Sur place')], default='none', max_length=20, verbose_name="mode d'encaissement"),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_due_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date limite du règlement demandé'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_amount_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='montant à reverser'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_blocked_reason',
            field=models.CharField(blank=True, max_length=220, verbose_name='raison blocage versement'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_ready_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='versement libérable le'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='versement envoyé le'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_status',
            field=models.CharField(choices=[('not_applicable', 'Aucun versement plateforme'), ('payout_pending', 'Versement en attente'), ('payout_ready', 'Versement libérable'), ('payout_released', 'Versement envoyé'), ('payout_blocked', 'Versement bloqué')], default='not_applicable', max_length=20, verbose_name='statut de versement praticien'),
        ),
        migrations.AddField(
            model_name='booking',
            name='platform_fee_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='commission plateforme'),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_charge_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='identifiant charge'),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_checkout_session_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='identifiant Checkout Session'),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_payment_intent_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='identifiant PaymentIntent'),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_payout_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='identifiant versement'),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_refund_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='identifiant remboursement'),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_transfer_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='identifiant transfert'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_decision_source',
            field=models.CharField(choices=[('none', 'Aucune décision'), ('automatic_policy', 'Politique automatique'), ('manual_practitioner', 'Décision praticien'), ('support', 'Support')], default='none', max_length=30, verbose_name='source de la décision de remboursement'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='prestation terminée le'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='prestation commencée le'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_validation_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='validation client demandée le'),
        ),
        migrations.AddField(
            model_name='booking',
            name='trust_exemption_applied',
            field=models.BooleanField(default=False, verbose_name='exemption accordée à un client de confiance'),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='currency',
            field=models.CharField(default='eur', max_length=3, verbose_name='devise'),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='is_live_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='provider_charge_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='provider_checkout_session_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='provider_payment_intent_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='provider_payout_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='provider_refund_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='provider_transfer_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='raw_provider_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='recorded_by_role',
            field=models.CharField(choices=[('client', 'Client'), ('practitioner', 'Praticien'), ('platform', 'Plateforme'), ('system', 'Système')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('none_required', 'Aucun paiement demandé'), ('payment_required', 'Paiement demandé'), ('deposit_required', 'Acompte attendu'), ('payment_pending', 'Paiement en attente'), ('payment_authorized', 'Autorisation enregistrée'), ('payment_captured', 'Paiement capturé'), ('partially_refunded', 'Remboursement partiel'), ('refunded', 'Remboursé'), ('canceled', 'Annulé')], default='none_required', max_length=20, verbose_name='statut de règlement'),
        ),
        migrations.AlterField(
            model_name='bookingpayment',
            name='kind',
            field=models.CharField(choices=[('deposit', 'Acompte'), ('full', 'Paiement total'), ('refund', 'Remboursement'), ('manual_collection', 'Règlement enregistré'), ('payout', 'Versement praticien')], max_length=20, verbose_name='type de règlement'),
        ),
        migrations.AlterField(
            model_name='bookingpayment',
            name='provider',
            field=models.CharField(choices=[('stripe_connect', 'Stripe Connect'), ('manual', 'Enregistrement manuel'), ('system', 'Système')], default='stripe_connect', max_length=30, verbose_name='prestataire'),
        ),
        migrations.AlterField(
            model_name='bookingpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('requires_action', 'Action requise'), ('authorized', 'Autorisé'), ('captured', 'Capturé'), ('partially_refunded', 'Partiellement remboursé'), ('refunded', 'Remboursé'), ('released', 'Versé'), ('failed', 'Échoué'), ('canceled', 'Annulé')], default='pending', max_length=20, verbose_name='statut'),
        ),
        migrations.RunPython(migrate_payment_statuses, migrations.RunPython.noop),
        migrations.CreateModel(
            name='BookingEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('actor_role', models.CharField(choices=[('client', 'Client'), ('practitioner', 'Praticien'), ('platform', 'Plateforme'), ('system', 'Système')], default='system', max_length=20)),
                ('event_type', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=220)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_events', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'événement de réservation',
                'verbose_name_plural': 'événements de réservation',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('provider', models.CharField(choices=[('stripe_connect', 'Stripe Connect'), ('manual', 'Enregistrement manuel'), ('system', 'Système')], max_length=30)),
                ('provider_event_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('processing_status', models.CharField(choices=[('received', 'Reçu'), ('processed', 'Traité'), ('failed', 'Échoué'), ('ignored', 'Ignoré')], default='received', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'journal webhook paiement',
                'verbose_name_plural': 'journaux webhook paiement',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrustedClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('first_name', models.CharField(max_length=120, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('waive_deposit', models.BooleanField(default=True, verbose_name='peut réserver sans acompte')),
                ('allow_pay_on_site', models.BooleanField(default=True, verbose_name='peut régler sur place')),
                ('notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_clients', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'client de confiance',
                'verbose_name_plural': 'clients de confiance',
                'constraints': [models.UniqueConstraint(fields=('professional', 'email'), name='unique_trusted_client_email_per_professional')],
            },
        ),
    ]
