# Generated by Django 6.0.3 on 2026-03-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_auto_completed_at_booking_canceled_by_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_no_show_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='absence client signalée le'),
        ),
        migrations.AddField(
            model_name='booking',
            name='issue_opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='signalement ouvert le'),
        ),
        migrations.AddField(
            model_name='booking',
            name='issue_opened_by_role',
            field=models.CharField(choices=[('client', 'Client'), ('practitioner', 'Praticien'), ('platform', 'Plateforme'), ('system', 'Système')], default='system', max_length=20, verbose_name='signalement ouvert par'),
        ),
        migrations.AddField(
            model_name='booking',
            name='issue_reason',
            field=models.CharField(blank=True, max_length=220, verbose_name='motif du signalement'),
        ),
        migrations.AddField(
            model_name='booking',
            name='practitioner_no_show_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='absence praticien signalée le'),
        ),
    ]
