# Generated by Django 6.0.3 on 2026-03-26 00:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_client_no_show_at_booking_issue_opened_at_and_more'),
        ('professionals', '0010_professionalprofile_facebook_url_and_more'),
        ('services', '0002_massageservice_service_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('client_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('practitioner_last_read_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'fil de discussion réservation',
                'verbose_name_plural': 'fils de discussion réservation',
            },
        ),
        migrations.CreateModel(
            name='BookingMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('sender_role', models.CharField(choices=[('client', 'Client'), ('practitioner', 'Praticien'), ('admin', 'Admin'), ('system', 'Système')], max_length=20)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('body', models.TextField(verbose_name='message')),
                ('contains_external_link', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('read_by_client_at', models.DateTimeField(blank=True, null=True)),
                ('read_by_practitioner_at', models.DateTimeField(blank=True, null=True)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bookings.bookingthread')),
            ],
            options={
                'verbose_name': 'message de réservation',
                'verbose_name_plural': 'messages de réservation',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='GuestBookingIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('client_first_name', models.CharField(max_length=120, verbose_name='prénom')),
                ('client_last_name', models.CharField(max_length=120, verbose_name='nom')),
                ('client_email', models.EmailField(max_length=254, verbose_name='email')),
                ('client_phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('client_note', models.TextField(blank=True, verbose_name='note client')),
                ('consent_cgu', models.BooleanField(default=False, verbose_name='CGU acceptées')),
                ('consent_cgv', models.BooleanField(default=False, verbose_name='CGV acceptées')),
                ('consent_cancellation_policy', models.BooleanField(default=False, verbose_name="politique d'annulation acceptée")),
                ('consented_at', models.DateTimeField(blank=True, null=True, verbose_name='consentement donné le')),
                ('consent_version', models.CharField(blank=True, max_length=40, verbose_name='version de consentement')),
                ('consent_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('verification_status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('expired', 'Expiré'), ('blocked', 'Bloqué'), ('completed', 'Réservation créée'), ('canceled', 'Annulé')], default='pending', max_length=20, verbose_name='statut de vérification email')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='email vérifié le')),
                ('last_verification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='dernier code envoyé le')),
                ('verification_resend_count', models.PositiveIntegerField(default=0, verbose_name='renvois')),
                ('booking_access_revoked', models.BooleanField(default=False, verbose_name='accès révoqué')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_identity_records', to='bookings.booking')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_booking_identities', to='professionals.professionalprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_booking_identities', to='services.massageservice')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_booking_identities', to='bookings.availabilityslot')),
            ],
            options={
                'verbose_name': 'identité invitée de réservation',
                'verbose_name_plural': 'identités invitées de réservation',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BookingEmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('code_hash', models.CharField(max_length=128, verbose_name='hash du code')),
                ('expires_at', models.DateTimeField(verbose_name='expire le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('expired', 'Expiré'), ('blocked', 'Bloqué')], default='pending', max_length=20, verbose_name='statut')),
                ('attempts_count', models.PositiveIntegerField(default=0, verbose_name='tentatives')),
                ('max_attempts', models.PositiveIntegerField(default=5, verbose_name='tentatives max')),
                ('sent_to_email', models.EmailField(max_length=254, verbose_name='email destinataire')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyé le')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='vérifié le')),
                ('guest_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to='bookings.guestbookingidentity')),
            ],
            options={
                'verbose_name': 'vérification email réservation',
                'verbose_name_plural': 'vérifications email réservation',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.guestbookingidentity'),
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('reporter_type', models.CharField(choices=[('client', 'Client'), ('practitioner', 'Praticien'), ('admin', 'Admin'), ('system', 'Système')], max_length=20)),
                ('reported_party_type', models.CharField(choices=[('client', 'Client'), ('practitioner', 'Praticien'), ('platform', 'Plateforme'), ('unknown', 'Non précisé')], default='unknown', max_length=20)),
                ('category', models.CharField(max_length=60, verbose_name='catégorie')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_review', 'En revue'), ('resolved', 'Résolu'), ('rejected', 'Rejeté')], default='open', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('payout_frozen', models.BooleanField(default=True, verbose_name='versement gelé')),
                ('admin_notes', models.TextField(blank=True, verbose_name='notes admin')),
                ('resolution', models.CharField(blank=True, max_length=120, verbose_name='résolution')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='résolu le')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='bookings.booking')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_incident_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'signalement de réservation',
                'verbose_name_plural': 'signalements de réservation',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IncidentEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('note', models.CharField(blank=True, max_length=220, verbose_name='note')),
                ('file', models.FileField(blank=True, upload_to='bookings/incidents/', verbose_name='fichier')),
                ('submitted_by_role', models.CharField(choices=[('client', 'Client'), ('practitioner', 'Praticien'), ('admin', 'Admin'), ('system', 'Système')], default='client', max_length=20)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='bookings.incidentreport')),
            ],
            options={
                'verbose_name': 'preuve de signalement',
                'verbose_name_plural': 'preuves de signalement',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='IncidentDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('decision_type', models.CharField(max_length=40, verbose_name='type de décision')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('amount_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='montant concerné')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_decisions', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='bookings.incidentreport')),
            ],
            options={
                'verbose_name': 'décision de signalement',
                'verbose_name_plural': 'décisions de signalement',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='RiskRegisterEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('subject_type', models.CharField(choices=[('practitioner', 'Praticien'), ('client_email', 'Client par email'), ('client_phone', 'Client par téléphone')], max_length=20)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('risk_level', models.CharField(choices=[('none', 'Aucun'), ('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('blocked', 'Bloqué')], default='none', max_length=20)),
                ('booking_restriction_status', models.CharField(choices=[('none', 'Aucune restriction'), ('review_required', 'Revue requise'), ('blocked', 'Bloqué')], default='none', max_length=20)),
                ('practitioner_trust_status', models.CharField(choices=[('none', 'Normal'), ('watch', 'Sous surveillance'), ('restricted', 'Restreint'), ('suspended', 'Suspendu')], default='none', max_length=20)),
                ('reason', models.CharField(max_length=220)),
                ('details', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_entries', to='bookings.booking')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_entries', to='professionals.professionalprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_risk_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrée registre de risque',
                'verbose_name_plural': 'registre de risque',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='guestbookingidentity',
            index=models.Index(fields=['client_email', 'verification_status'], name='bookings_gu_client__fbc8ef_idx'),
        ),
        migrations.AddIndex(
            model_name='guestbookingidentity',
            index=models.Index(fields=['slot', 'verification_status'], name='bookings_gu_slot_id_02ea2b_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingemailverification',
            index=models.Index(fields=['guest_identity', 'status'], name='bookings_bo_guest_i_563d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingemailverification',
            index=models.Index(fields=['expires_at'], name='bookings_bo_expires_2b15ce_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['booking', 'status'], name='bookings_in_booking_ed8710_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['severity', 'status'], name='bookings_in_severit_10b83f_idx'),
        ),
        migrations.AddIndex(
            model_name='riskregisterentry',
            index=models.Index(fields=['subject_type', 'risk_level', 'is_active'], name='bookings_ri_subject_2be053_idx'),
        ),
        migrations.AddIndex(
            model_name='riskregisterentry',
            index=models.Index(fields=['client_email', 'is_active'], name='bookings_ri_client__e2746d_idx'),
        ),
        migrations.AddIndex(
            model_name='riskregisterentry',
            index=models.Index(fields=['professional', 'is_active'], name='bookings_ri_profess_4a2925_idx'),
        ),
    ]
