# Generated by Django 6.0.3 on 2026-03-26 13:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookingthread_bookingmessage_guestbookingidentity_and_more'),
        ('professionals', '0013_directoryinterestlead_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRestriction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('subject_type', models.CharField(choices=[('practitioner', 'Praticien'), ('client_email', 'Client par email'), ('client_phone', 'Client par téléphone'), ('user', 'Utilisateur')], max_length=20)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('restriction_type', models.CharField(choices=[('warning', 'Avertissement'), ('booking_review', 'Réservation sous revue'), ('booking_blocked', 'Réservation bloquée'), ('payout_suspended', 'Versement suspendu'), ('account_suspended', 'Compte suspendu'), ('banned', 'Bannissement')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expirée'), ('revoked', 'Révoquée')], default='active', max_length=20)),
                ('reason', models.CharField(max_length=220)),
                ('notes', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_account_restrictions', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restrictions', to='bookings.incidentreport')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_restrictions', to='professionals.professionalprofile')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_account_restrictions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_restrictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'restriction de compte',
                'verbose_name_plural': 'restrictions de compte',
                'ordering': ('-created_at',),
                'permissions': [('moderate_incidents', 'Can moderate incidents'), ('manage_restrictions', 'Can manage account restrictions')],
                'indexes': [models.Index(fields=['subject_type', 'status'], name='bookings_ac_subject_77120c_idx'), models.Index(fields=['professional', 'status'], name='bookings_ac_profess_aa73ba_idx'), models.Index(fields=['client_email', 'status'], name='bookings_ac_client__a1d87a_idx'), models.Index(fields=['user', 'status'], name='bookings_ac_user_id_09ae1c_idx')],
            },
        ),
    ]
