"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import importlib.util
import os
import sys
from urllib.parse import parse_qs, unquote, urlparse

BASE_DIR = Path(__file__).resolve().parent.parent
TESTING = "test" in sys.argv


def build_database_config():
    database_url = os.getenv("DATABASE_URL", "").strip()
    if not database_url:
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }

    parsed = urlparse(database_url)
    scheme = parsed.scheme.split("+")[0]

    if scheme in {"postgres", "postgresql", "pgsql"}:
        options = {}
        query = parse_qs(parsed.query)
        sslmode = query.get("sslmode", [None])[-1]
        if sslmode:
            options["sslmode"] = sslmode
        elif not DEBUG:
            options["sslmode"] = "require"

        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote(parsed.path.lstrip("/")),
            "USER": unquote(parsed.username or ""),
            "PASSWORD": unquote(parsed.password or ""),
            "HOST": parsed.hostname or "",
            "PORT": str(parsed.port or "5432"),
            "CONN_MAX_AGE": 60,
            "OPTIONS": options,
        }

    if scheme == "sqlite":
        sqlite_path = unquote(parsed.path or "").lstrip("/")
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / sqlite_path if sqlite_path else BASE_DIR / "db.sqlite3",
        }

    raise ValueError(f"Schéma DATABASE_URL non pris en charge: {scheme}")

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-change-me")
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "http://localhost:3000").split(",")
    if origin.strip()
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",

    "common",
    "accounts",
    "assistant",
    "professionals",
    "services",
    "bookings",
    "reviews",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

DATABASES = {"default": build_database_config()}

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "fr-fr"
TIME_ZONE = "Europe/Paris"
USE_I18N = True
USE_TZ = True

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
DJANGO_ENABLE_WHITENOISE = (
    os.getenv("DJANGO_ENABLE_WHITENOISE", "false" if DEBUG else "true").lower()
    == "true"
)
WHITENOISE_INSTALLED = importlib.util.find_spec("whitenoise") is not None

if DJANGO_ENABLE_WHITENOISE and WHITENOISE_INSTALLED:
    MIDDLEWARE.insert(2, "whitenoise.middleware.WhiteNoiseMiddleware")
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

SECURE_SSL_REDIRECT = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "false" if DEBUG else "true").lower() == "true"
SESSION_COOKIE_SECURE = os.getenv("DJANGO_SESSION_COOKIE_SECURE", "false" if DEBUG else "true").lower() == "true"
CSRF_COOKIE_SECURE = os.getenv("DJANGO_CSRF_COOKIE_SECURE", "false" if DEBUG else "true").lower() == "true"
SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "0" if DEBUG else "31536000"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "false" if DEBUG else "true").lower() == "true"
SECURE_HSTS_PRELOAD = os.getenv("DJANGO_SECURE_HSTS_PRELOAD", "false").lower() == "true"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

EMAIL_BACKEND = os.getenv(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"
    if DEBUG
    else "django.core.mail.backends.smtp.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.getenv(
    "DJANGO_DEFAULT_FROM_EMAIL",
    "NUADYX <bonjour@nuadyx.app>",
)
EMAIL_HOST = os.getenv("DJANGO_EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("DJANGO_EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("DJANGO_EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("DJANGO_EMAIL_USE_TLS", "true").lower() == "true"
FRONTEND_APP_URL = os.getenv("FRONTEND_APP_URL", "http://localhost:3000")
NUADYX_STRIPE_SECRET_KEY = os.getenv("NUADYX_STRIPE_SECRET_KEY", "")
NUADYX_STRIPE_PUBLISHABLE_KEY = os.getenv("NUADYX_STRIPE_PUBLISHABLE_KEY", "")
NUADYX_STRIPE_WEBHOOK_SECRET = os.getenv("NUADYX_STRIPE_WEBHOOK_SECRET", "")
NUADYX_STRIPE_INTERNAL_TEST_MODE = (
    os.getenv("NUADYX_STRIPE_INTERNAL_TEST_MODE", "true" if DEBUG else "false").lower()
    == "true"
)
NUADYX_PLATFORM_FEE_RATE = os.getenv("NUADYX_PLATFORM_FEE_RATE", "0.10")
NUADYX_PAYMENT_HOLD_MINUTES = int(os.getenv("NUADYX_PAYMENT_HOLD_MINUTES", "30"))
NUADYX_AUTO_RELEASE_AFTER_HOURS = int(os.getenv("NUADYX_AUTO_RELEASE_AFTER_HOURS", "48"))
NUADYX_FEATURE_COOKIE_CONSENT = (
    os.getenv("NUADYX_FEATURE_COOKIE_CONSENT", "true").lower() == "true"
)
NUADYX_FEATURE_PRACTITIONER_VERIFICATION = (
    os.getenv("NUADYX_FEATURE_PRACTITIONER_VERIFICATION", "true").lower() == "true"
)
NUADYX_FEATURE_REVIEW_REPLIES = (
    os.getenv("NUADYX_FEATURE_REVIEW_REPLIES", "true").lower() == "true"
)

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.User"

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("DJANGO_CORS_ALLOWED_ORIGINS", "http://localhost:3000").split(",")
    if origin.strip()
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}
