# Generated by Django 6.0.3 on 2026-03-22 13:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassageService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('title', models.CharField(max_length=160, verbose_name='titre')),
                ('short_description', models.CharField(max_length=255, verbose_name='description courte')),
                ('full_description', models.TextField(blank=True, verbose_name='description complète')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='durée (minutes)')),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='prix (€)')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('sort_order', 'duration_minutes', 'title'),
            },
        ),
    ]
