# Generated by Django 6.0.3 on 2026-03-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massageservice',
            name='service_category',
            field=models.CharField(blank=True, choices=[('', 'Non précisée'), ('relaxant', 'Massage relaxant'), ('deep_tissue', 'Deep tissue'), ('tantrique', 'Tantrique')], default='', max_length=30, verbose_name='catégorie principale'),
        ),
    ]
