# Generated by Django 6.0.3 on 2026-03-26 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('professionals', '0012_locationindex_insee_code_locationindex_region_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityGrowthPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('city_label', models.CharField(max_length=160)),
                ('city_slug', models.SlugField(max_length=170, unique=True)),
                ('department_code', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('objective_profiles_total', models.PositiveIntegerField(default=10)),
                ('objective_claimed_profiles', models.PositiveIntegerField(default=4)),
                ('objective_active_profiles', models.PositiveIntegerField(default=3)),
                ('priority_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('growth_status', models.CharField(choices=[('empty', 'Vide'), ('seed', 'Amorcée'), ('building', 'En croissance'), ('healthy', 'Saine'), ('saturated', 'Saturée'), ('deprioritized', 'Dépriorisée')], default='seed', max_length=20)),
                ('notes_internal', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'plan de croissance ville',
                'verbose_name_plural': 'plans de croissance villes',
                'ordering': ('city_label',),
            },
        ),
        migrations.AddField(
            model_name='contactcampaign',
            name='campaign_scope_type',
            field=models.CharField(choices=[('global', 'Global'), ('city', 'Ville'), ('department', 'Département'), ('region', 'Région'), ('source', 'Source')], default='global', max_length=20),
        ),
        migrations.AddField(
            model_name='contactcampaign',
            name='campaign_scope_value',
            field=models.CharField(blank=True, max_length=170),
        ),
        migrations.AddField(
            model_name='contactcampaign',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contactcampaign',
            name='department_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='contactcampaign',
            name='region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='contactcampaign',
            index=models.Index(fields=['city'], name='directory_c_city_8e5f68_idx'),
        ),
        migrations.AddIndex(
            model_name='contactcampaign',
            index=models.Index(fields=['department_code'], name='directory_c_departm_cd08c1_idx'),
        ),
        migrations.AddIndex(
            model_name='contactcampaign',
            index=models.Index(fields=['region'], name='directory_c_region_1ee49b_idx'),
        ),
        migrations.AddIndex(
            model_name='contactcampaign',
            index=models.Index(fields=['campaign_scope_type', 'campaign_scope_value'], name='directory_c_campaig_b58ccd_idx'),
        ),
        migrations.AddField(
            model_name='citygrowthplan',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='city_growth_plan', to='professionals.locationindex'),
        ),
        migrations.AddIndex(
            model_name='citygrowthplan',
            index=models.Index(fields=['city_slug'], name='directory_c_city_sl_304f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='citygrowthplan',
            index=models.Index(fields=['priority_level'], name='directory_c_priorit_e0eec2_idx'),
        ),
        migrations.AddIndex(
            model_name='citygrowthplan',
            index=models.Index(fields=['growth_status'], name='directory_c_growth__4f3c52_idx'),
        ),
        migrations.AddIndex(
            model_name='citygrowthplan',
            index=models.Index(fields=['department_code'], name='directory_c_departm_264137_idx'),
        ),
        migrations.AddIndex(
            model_name='citygrowthplan',
            index=models.Index(fields=['region'], name='directory_c_region_a8ee1c_idx'),
        ),
    ]
