# Generated by Django 6.0.3 on 2026-03-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_citygrowthplan_contactcampaign_campaign_scope_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcampaign',
            name='budget_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contactcampaign',
            name='campaign_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('claim_invite', 'Invitation de revendication'), ('incomplete_profile_nudge', 'Relance fiche incomplète'), ('source_recontact', 'Recontact source'), ('seo', 'SEO local'), ('boost', 'Mise en avant'), ('acquisition', 'Acquisition'), ('email', 'Email')], max_length=30),
        ),
    ]
