# Generated by Django 6.0.3 on 2026-03-22 13:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('business_name', models.CharField(max_length=160, verbose_name='nom affiché')),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Le slug ne peut contenir que des lettres minuscules, chiffres et tirets.', regex='^[a-z0-9-]+$')], verbose_name='slug public')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('bio', models.TextField(blank=True, verbose_name='présentation')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('public_email', models.EmailField(blank=True, max_length=254, verbose_name='email public')),
                ('is_public', models.BooleanField(default=True, verbose_name='profil public')),
                ('accepts_online_booking', models.BooleanField(default=True, verbose_name='réservation en ligne active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil professionnel',
                'verbose_name_plural': 'profils professionnels',
            },
        ),
    ]
