# Generated by Django 6.0.3 on 2026-03-22 16:04

import django.core.validators
import professionals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='cover_photo',
            field=models.FileField(blank=True, upload_to=professionals.models.professional_cover_photo_upload_to, verbose_name='photo de couverture'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to=professionals.models.professional_profile_photo_upload_to, verbose_name='photo de profil'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='public_headline',
            field=models.CharField(blank=True, max_length=180, verbose_name='accroche publique'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='specialties',
            field=models.JSONField(blank=True, default=list, verbose_name='spécialités'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='visual_theme',
            field=models.CharField(choices=[('epure', 'Épure'), ('chaleur', 'Chaleur'), ('prestige', 'Prestige')], default='epure', max_length=20, verbose_name='thème visuel'),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Le slug ne peut contenir que des lettres minuscules, chiffres et tirets.', regex='^[a-z0-9-]+$'), professionals.models.validate_public_slug], verbose_name='slug public'),
        ),
    ]
