# Generated by Django 6.0.3 on 2026-03-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_professionalprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='activity_type',
            field=models.CharField(choices=[('solo', 'Praticien solo'), ('studio', 'Cabinet / studio'), ('spa', 'Spa / institut'), ('team', 'Équipe de praticiens')], default='solo', max_length=20, verbose_name="type d'activité"),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='accompagnement terminé'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='onboarding_step',
            field=models.CharField(choices=[('welcome', 'Bienvenue'), ('activity', 'Activité'), ('services', 'Prestations'), ('setting', "Cadre d'accueil"), ('slots', 'Créneaux'), ('ready', 'Prêt')], default='welcome', max_length=20, verbose_name="étape d'accompagnement"),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='practice_mode',
            field=models.CharField(choices=[('studio', 'En cabinet / studio'), ('home', 'À domicile'), ('mobile', 'En déplacement / itinérant'), ('corporate', 'En entreprise / en événementiel'), ('mixed', 'Mixte')], default='studio', max_length=20, verbose_name="façon d'exercer"),
        ),
    ]
