# Generated by Django 6.0.3 on 2026-03-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_professionalprofile_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='access_details',
            field=models.TextField(blank=True, verbose_name='accès et repères'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='ambience_details',
            field=models.TextField(blank=True, verbose_name='ambiance et cadre'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='client_preparation',
            field=models.TextField(blank=True, verbose_name='ce que le client doit prévoir'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='equipment_provided',
            field=models.TextField(blank=True, verbose_name='ce que le praticien apporte'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='highlight_points',
            field=models.JSONField(blank=True, default=list, verbose_name='points forts'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='ideal_for',
            field=models.TextField(blank=True, verbose_name='pour qui ou pour quoi le praticien reçoit'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='service_area',
            field=models.CharField(blank=True, max_length=180, verbose_name='zone desservie'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='venue_details',
            field=models.TextField(blank=True, verbose_name="lieu d'accueil"),
        ),
    ]
