# Generated by Django 6.0.3 on 2026-03-23 23:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0004_professionalprofile_access_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='deposit_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="montant ou pourcentage d'acompte"),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='deposit_value_type',
            field=models.CharField(choices=[('fixed', 'Montant fixe'), ('percentage', 'Pourcentage')], default='fixed', max_length=20, verbose_name="type de valeur d'acompte"),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='free_cancellation_notice_hours',
            field=models.PositiveIntegerField(default=24, verbose_name="annulation sans frais jusqu'à"),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='keep_payment_after_deadline',
            field=models.BooleanField(default=True, verbose_name='conserver le règlement après le délai'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='payment_message',
            field=models.CharField(blank=True, max_length=220, verbose_name='message rassurant sur le règlement'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='reservation_payment_mode',
            field=models.CharField(choices=[('none', 'Sans paiement à la réservation'), ('deposit', 'Avec acompte'), ('full', 'Avec paiement total')], default='none', max_length=20, verbose_name='mode de règlement à la réservation'),
        ),
    ]
