# Generated by Django 6.0.3 on 2026-03-24 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0005_professionalprofile_deposit_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalPaymentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('provider', models.CharField(choices=[('stripe_connect', 'Stripe Connect')], default='stripe_connect', max_length=30, verbose_name='prestataire de paiement')),
                ('onboarding_status', models.CharField(choices=[('not_started', 'Non commencé'), ('pending', 'En attente'), ('active', 'Actif'), ('restricted', 'Restreint')], default='not_started', max_length=20, verbose_name='statut du compte de paiement')),
                ('stripe_account_id', models.CharField(blank=True, max_length=80, verbose_name='identifiant Stripe')),
                ('account_email', models.EmailField(blank=True, max_length=254, verbose_name='email du compte de paiement')),
                ('country', models.CharField(default='FR', max_length=2, verbose_name='pays')),
                ('default_currency', models.CharField(default='eur', max_length=3, verbose_name='devise')),
                ('details_submitted', models.BooleanField(default=False, verbose_name='informations transmises')),
                ('charges_enabled', models.BooleanField(default=False, verbose_name='encaissements activés')),
                ('payouts_enabled', models.BooleanField(default=False, verbose_name='versements activés')),
                ('last_onboarding_link_requested_at', models.DateTimeField(blank=True, null=True, verbose_name="dernier lien d'activation demandé")),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_account', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'compte de paiement professionnel',
                'verbose_name_plural': 'comptes de paiement professionnels',
            },
        ),
    ]
