# Generated by Django 6.0.3 on 2026-03-25 14:11

import django.db.models.deletion
import professionals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0006_professionalpaymentaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('status', models.CharField(choices=[('not_started', 'Non commencé'), ('pending', 'En attente'), ('in_review', 'En revue'), ('verified', 'Vérifié'), ('rejected', 'Refusé'), ('expired', 'Expiré')], default='not_started', max_length=20, verbose_name='statut KYC')),
                ('siren', models.CharField(blank=True, max_length=20, verbose_name='SIREN')),
                ('siret', models.CharField(blank=True, max_length=20, verbose_name='SIRET')),
                ('beneficiary_name', models.CharField(blank=True, max_length=180, verbose_name='bénéficiaire')),
                ('iban_last4', models.CharField(blank=True, max_length=4, verbose_name='4 derniers chiffres IBAN')),
                ('identity_document', models.FileField(blank=True, upload_to=professionals.models.verification_identity_document_upload_to, verbose_name="pièce d'identité")),
                ('selfie_document', models.FileField(blank=True, upload_to=professionals.models.verification_selfie_upload_to, verbose_name='selfie de vérification')),
                ('activity_document', models.FileField(blank=True, upload_to=professionals.models.verification_activity_upload_to, verbose_name="justificatif d'activité")),
                ('liability_insurance_document', models.FileField(blank=True, upload_to=professionals.models.verification_insurance_upload_to, verbose_name='attestation RC Pro')),
                ('iban_document', models.FileField(blank=True, upload_to=professionals.models.verification_iban_upload_to, verbose_name='justificatif bancaire')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='soumis le')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='revue le')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='vérifié le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expire le')),
                ('rejection_reason', models.CharField(blank=True, max_length=280, verbose_name='motif de refus')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'vérification praticien',
                'verbose_name_plural': 'vérifications praticiens',
            },
        ),
        migrations.CreateModel(
            name='PractitionerVerificationDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='ancien statut')),
                ('to_status', models.CharField(max_length=20, verbose_name='nouveau statut')),
                ('reason', models.CharField(blank=True, max_length=280, verbose_name='motif')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioner_verification_decisions', to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='professionals.practitionerverification')),
            ],
            options={
                'verbose_name': 'décision de vérification',
                'verbose_name_plural': 'décisions de vérification',
                'ordering': ('-created_at',),
            },
        ),
    ]
