# Generated by Django 6.0.3 on 2026-03-25 15:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import professionals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0007_practitionerverification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryInterestLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('kind', models.CharField(choices=[('suggest_practitioner', 'Suggérer un praticien'), ('recommend_masseur', 'Recommander mon masseur'), ('city_waitlist', "Prévenu à l'ouverture")], max_length=40, verbose_name='type de demande')),
                ('full_name', models.CharField(max_length=160, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('practitioner_name', models.CharField(blank=True, max_length=160, verbose_name='praticien suggéré')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('source_page', models.CharField(blank=True, max_length=200, verbose_name='page source')),
                ('processed', models.BooleanField(default=False, verbose_name='traité')),
            ],
            options={
                'verbose_name': 'lead annuaire',
                'verbose_name_plural': 'leads annuaire',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DirectoryProfileCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('status', models.CharField(choices=[('draft_imported', 'Brouillon importé'), ('pending_review', 'En revue'), ('published_unclaimed', 'Publié non revendiqué'), ('claimed', 'Revendiqué'), ('removed', 'Retiré')], default='draft_imported', max_length=30, verbose_name='statut de fiche')),
                ('business_name', models.CharField(max_length=160, verbose_name='nom affiché')),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Le slug ne peut contenir que des lettres minuscules, chiffres et tirets.', regex='^[a-z0-9-]+$'), professionals.models.validate_public_slug], verbose_name='slug public')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('service_area', models.CharField(blank=True, max_length=180, verbose_name='zone desservie')),
                ('public_headline', models.CharField(blank=True, max_length=180, verbose_name='accroche publique')),
                ('bio', models.TextField(blank=True, verbose_name='présentation')),
                ('specialties', models.JSONField(blank=True, default=list, verbose_name='spécialités')),
                ('massage_categories', models.JSONField(blank=True, default=list, verbose_name='catégories massage')),
                ('public_email', models.EmailField(blank=True, max_length=254, verbose_name='email public')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone public')),
                ('source_label', models.CharField(blank=True, max_length=120, verbose_name='source')),
                ('source_url', models.URLField(blank=True, verbose_name='source_url')),
                ('source_payload', models.JSONField(blank=True, default=dict, verbose_name='payload source')),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='importé le')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publié le')),
                ('claim_token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='claim_token')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='revendiqué le')),
                ('removal_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='suppression demandée le')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('linked_professional', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_candidate', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'fiche candidate annuaire',
                'verbose_name_plural': 'fiches candidates annuaire',
                'ordering': ('business_name',),
            },
        ),
        migrations.CreateModel(
            name='DirectoryProfileClaimRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('claimant_name', models.CharField(max_length=160, verbose_name='nom du demandeur')),
                ('claimant_email', models.EmailField(max_length=254, verbose_name='email du demandeur')),
                ('claimant_phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone du demandeur')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='pending', max_length=20, verbose_name='statut')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
                ('review_notes', models.TextField(blank=True, verbose_name='notes de traitement')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='professionals.directoryprofilecandidate')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_claim_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'demande de revendication',
                'verbose_name_plural': 'demandes de revendication',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DirectoryProfileRemovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('requester_name', models.CharField(max_length=160, verbose_name='nom du demandeur')),
                ('requester_email', models.EmailField(max_length=254, verbose_name='email du demandeur')),
                ('reason', models.TextField(blank=True, verbose_name='motif')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Traitée')], default='pending', max_length=20, verbose_name='statut')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_requests', to='professionals.directoryprofilecandidate')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_removal_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'demande de suppression de fiche',
                'verbose_name_plural': 'demandes de suppression de fiche',
                'ordering': ('-created_at',),
            },
        ),
    ]
