# Generated by Django 6.0.3 on 2026-03-25 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('professionals', '0008_directoryinterestlead_directoryprofilecandidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='acquisition_source',
            field=models.CharField(choices=[('direct_signup', 'Inscription directe'), ('imported_claimed', 'Fiche importée revendiquée'), ('admin_created', 'Créé par admin'), ('referral', 'Par recommandation')], default='direct_signup', max_length=20, verbose_name="source d'acquisition"),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='imported_profile_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_professional_profiles', to='directory.importedprofile'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='profile_claimed_from_import',
            field=models.BooleanField(default=False, verbose_name='profil revendiqué depuis import'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='verification_badge_status',
            field=models.CharField(choices=[('none', 'Aucun'), ('pending', 'En attente'), ('verified', 'Vérifié'), ('suspended', 'Suspendu'), ('expired', 'Expiré')], default='none', max_length=20, verbose_name='statut du badge public'),
        ),
    ]
