# Generated by Django 6.0.3 on 2026-03-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0009_professionalprofile_acquisition_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='site web'),
        ),
    ]
