# Generated by Django 6.0.3 on 2026-03-26 01:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0010_professionalprofile_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestFavoriteCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('access_token', models.CharField(editable=False, max_length=64, unique=True, verbose_name="jeton d'accès")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='dernier accès')),
            ],
            options={
                'verbose_name': 'collection de favoris invité',
                'verbose_name_plural': 'collections de favoris invité',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('label', models.CharField(max_length=40, verbose_name='libellé')),
                ('normalized_label', models.CharField(editable=False, max_length=40, verbose_name='libellé normalisé')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_tags', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'tag contact',
                'verbose_name_plural': 'tags contacts',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='FavoritePractitioner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='professionals.professionalprofile')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='professionals.guestfavoritecollection')),
            ],
            options={
                'verbose_name': 'praticien favori',
                'verbose_name_plural': 'praticiens favoris',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LocationIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('location_type', models.CharField(choices=[('city', 'Ville'), ('postal_code', 'Code postal'), ('department', 'Département'), ('region', 'Région'), ('country', 'Pays')], max_length=20, verbose_name='type de localisation')),
                ('label', models.CharField(max_length=160, verbose_name='libellé')),
                ('normalized_label', models.CharField(editable=False, max_length=160, verbose_name='libellé normalisé')),
                ('slug', models.SlugField(max_length=170, verbose_name='slug')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='code postal')),
                ('department_code', models.CharField(blank=True, max_length=10, verbose_name='code département')),
                ('department_name', models.CharField(blank=True, max_length=120, verbose_name='département')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='région')),
                ('country', models.CharField(blank=True, default='France', max_length=120, verbose_name='pays')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='priorité')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'index de localisation',
                'verbose_name_plural': 'index de localisation',
                'ordering': ('-priority', 'label'),
                'indexes': [models.Index(fields=['normalized_label'], name='professiona_normali_801de0_idx'), models.Index(fields=['location_type', 'priority'], name='professiona_locatio_13e2d3_idx'), models.Index(fields=['postal_code'], name='professiona_postal__46ba3e_idx')],
                'constraints': [models.UniqueConstraint(fields=('location_type', 'slug', 'postal_code'), name='unique_location_index_entry')],
            },
        ),
        migrations.CreateModel(
            name='PractitionerContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('normalized_email', models.CharField(editable=False, max_length=255, verbose_name='email normalisé')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('booking_count', models.PositiveIntegerField(default=0, verbose_name='nombre de réservations')),
                ('validated_booking_count', models.PositiveIntegerField(default=0, verbose_name='prestations validées')),
                ('canceled_booking_count', models.PositiveIntegerField(default=0, verbose_name='annulations')),
                ('no_show_count', models.PositiveIntegerField(default=0, verbose_name='no-show')),
                ('disputed_booking_count', models.PositiveIntegerField(default=0, verbose_name='litiges')),
                ('first_booking_at', models.DateTimeField(blank=True, null=True, verbose_name='première réservation')),
                ('last_booking_at', models.DateTimeField(blank=True, null=True, verbose_name='dernière réservation')),
                ('last_validated_at', models.DateTimeField(blank=True, null=True, verbose_name='dernière prestation validée')),
                ('segment', models.CharField(choices=[('new', 'Nouveau'), ('active', 'Actif'), ('loyal', 'Fidèle'), ('never_seen', 'Jamais vu'), ('canceled', 'A annulé'), ('no_show', 'No-show'), ('watch', 'À surveiller'), ('dispute', 'Avec litige'), ('blocked', 'Bloqué'), ('inactive', 'Inactif')], default='new', max_length=20, verbose_name='segment principal')),
                ('segment_score', models.IntegerField(default=0, verbose_name='score de segment')),
                ('segment_reasons_json', models.JSONField(blank=True, default=list, verbose_name='raisons du segment')),
                ('risk_level', models.CharField(choices=[('none', 'Aucun'), ('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('blocked', 'Bloqué')], default='none', max_length=20, verbose_name='niveau de risque')),
                ('is_trusted', models.BooleanField(default=False, verbose_name='client de confiance')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='professionals.professionalprofile')),
                ('tags', models.ManyToManyField(blank=True, related_name='contacts', to='professionals.contacttag')),
            ],
            options={
                'verbose_name': 'contact praticien',
                'verbose_name_plural': 'contacts praticiens',
                'ordering': ('first_name', 'last_name', 'email'),
            },
        ),
        migrations.CreateModel(
            name='ContactPrivateNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('content', models.TextField(blank=True, max_length=600, verbose_name='note privée')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_note', to='professionals.practitionercontact')),
            ],
            options={
                'verbose_name': 'note privée contact',
                'verbose_name_plural': 'notes privées contacts',
            },
        ),
        migrations.AddConstraint(
            model_name='contacttag',
            constraint=models.UniqueConstraint(fields=('professional', 'normalized_label'), name='unique_contact_tag_per_professional'),
        ),
        migrations.AddConstraint(
            model_name='favoritepractitioner',
            constraint=models.UniqueConstraint(fields=('collection', 'professional'), name='unique_favorite_professional_per_collection'),
        ),
        migrations.AddIndex(
            model_name='practitionercontact',
            index=models.Index(fields=['professional', 'segment'], name='professiona_profess_dd27a1_idx'),
        ),
        migrations.AddIndex(
            model_name='practitionercontact',
            index=models.Index(fields=['professional', 'risk_level'], name='professiona_profess_5274bb_idx'),
        ),
        migrations.AddIndex(
            model_name='practitionercontact',
            index=models.Index(fields=['professional', 'last_booking_at'], name='professiona_profess_aeabb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='practitionercontact',
            constraint=models.UniqueConstraint(fields=('professional', 'normalized_email'), name='unique_practitioner_contact_email'),
        ),
    ]
