# Generated by Django 6.0.3 on 2026-03-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0011_guestfavoritecollection_contacttag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationindex',
            name='insee_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='code INSEE'),
        ),
        migrations.AddField(
            model_name='locationindex',
            name='region_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='code région'),
        ),
        migrations.AddField(
            model_name='locationindex',
            name='search_text',
            field=models.TextField(blank=True, editable=False, verbose_name='texte de recherche'),
        ),
        migrations.AddIndex(
            model_name='locationindex',
            index=models.Index(fields=['department_code'], name='professiona_departm_f6e532_idx'),
        ),
        migrations.AddIndex(
            model_name='locationindex',
            index=models.Index(fields=['region_code'], name='professiona_region__c387d3_idx'),
        ),
    ]
