# Generated by Django 6.0.3 on 2026-03-26 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_citygrowthplan_contactcampaign_campaign_scope_type_and_more'),
        ('professionals', '0012_locationindex_insee_code_locationindex_region_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryinterestlead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_directory_interest_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directoryinterestlead',
            name='city_slug',
            field=models.SlugField(blank=True, max_length=140, verbose_name='slug ville'),
        ),
        migrations.AddField(
            model_name='directoryinterestlead',
            name='converted_to_imported_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_interest_leads', to='directory.importedprofile'),
        ),
        migrations.AddField(
            model_name='directoryinterestlead',
            name='location_type',
            field=models.CharField(choices=[('city', 'Ville'), ('department', 'Département'), ('region', 'Région'), ('postal_code', 'Code postal')], default='city', max_length=20, verbose_name='type de localisation'),
        ),
        migrations.AddField(
            model_name='directoryinterestlead',
            name='ops_notes',
            field=models.TextField(blank=True, verbose_name='notes ops'),
        ),
        migrations.AddField(
            model_name='directoryinterestlead',
            name='ops_status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('in_review', 'En revue'), ('converted', 'Converti'), ('ignored', 'Ignoré'), ('contacted', 'Contacté')], default='new', max_length=20, verbose_name='statut ops'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='department_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='code département'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='code postal'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='region',
            field=models.CharField(blank=True, max_length=120, verbose_name='région'),
        ),
        migrations.AddIndex(
            model_name='directoryinterestlead',
            index=models.Index(fields=['city_slug'], name='professiona_city_sl_f5338a_idx'),
        ),
        migrations.AddIndex(
            model_name='directoryinterestlead',
            index=models.Index(fields=['ops_status'], name='professiona_ops_sta_a92e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='directoryinterestlead',
            index=models.Index(fields=['processed'], name='professiona_process_2888b9_idx'),
        ),
    ]
