# Generated by Django 6.0.3 on 2026-03-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0013_directoryinterestlead_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='manual_visibility_boost',
            field=models.IntegerField(default=0, verbose_name='ajustement manuel de visibilité'),
        ),
    ]
