# Generated by Django 6.0.3 on 2026-03-24 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_booking_auto_completed_at_booking_canceled_by_role_and_more'),
        ('professionals', '0006_professionalpaymentaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(choices=[('manual', 'Invitation manuelle'), ('booking', 'Après réservation'), ('legacy', 'Client historique')], default='manual', max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_invitations', to='bookings.booking')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_invitations_created', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_invitations', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': "invitation d'avis",
                'verbose_name_plural': "invitations d'avis",
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('invited_customer_email', models.EmailField(blank=True, max_length=254)),
                ('author_name', models.CharField(max_length=160)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('published', 'Publié'), ('rejected', 'Refusé'), ('flagged', 'Signalé')], default='published', max_length=20)),
                ('verification_type', models.CharField(choices=[('booked_on_platform', 'Réservation vérifiée'), ('invited_by_practitioner', 'Client invité'), ('imported_legacy_customer', 'Client historique')], default='invited_by_practitioner', max_length=30)),
                ('moderation_flags', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='bookings.booking')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='professionals.professionalprofile')),
                ('invitation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='reviews.reviewinvitation')),
            ],
            options={
                'verbose_name': 'avis client',
                'verbose_name_plural': 'avis clients',
                'ordering': ('-published_at', '-created_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('booking__isnull', False)), fields=('booking',), name='unique_review_per_booking')],
            },
        ),
    ]
