# Generated by Django 6.0.3 on 2026-03-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='flag_reason',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='review',
            name='submitted_from_ip_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='review',
            name='submitted_from_user_agent_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reviewinvitation',
            name='usage_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
