# Generated by Django 6.0.3 on 2026-03-25 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_review_statuses(apps, schema_editor):
    Review = apps.get_model("reviews", "Review")
    Review.objects.filter(status="published").update(status="approved")
    Review.objects.filter(status="flagged").update(status="hidden")


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_flag_reason_review_submitted_from_ip_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='experience_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='practitioner_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='practitioner_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(choices=[('booking', 'Réservation'), ('invitation', 'Invitation'), ('legacy', 'Historique')], default='invitation', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé'), ('hidden', 'Masqué')], default='pending', max_length=20),
        ),
        migrations.RunPython(migrate_legacy_review_statuses, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ReviewModerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('action', models.CharField(choices=[('submitted', 'Soumis'), ('flagged', 'Signalé'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('hidden', 'Masqué'), ('response_added', 'Réponse praticien')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=220)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_moderation_logs', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='reviews.review')),
            ],
            options={
                'verbose_name': "journal de modération d'avis",
                'verbose_name_plural': "journaux de modération d'avis",
                'ordering': ('-created_at',),
            },
        ),
    ]
