# Generated by Django 6.0.3 on 2026-03-22 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0002_professionalprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalAssistantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('activity_overview', models.TextField(blank=True, verbose_name="présentation de l'activité")),
                ('support_style', models.TextField(blank=True, verbose_name="style d'accompagnement")),
                ('practice_information', models.TextField(blank=True, verbose_name="informations sur le cabinet ou le lieu d'accueil")),
                ('faq_items', models.JSONField(blank=True, default=list, verbose_name='questions fréquentes')),
                ('before_session', models.TextField(blank=True, verbose_name='avant la séance')),
                ('after_session', models.TextField(blank=True, verbose_name='après la séance')),
                ('service_information', models.TextField(blank=True, verbose_name='informations sur les prestations')),
                ('booking_policy', models.TextField(blank=True, verbose_name='réservation et annulation')),
                ('contact_information', models.TextField(blank=True, verbose_name='informations de contact utiles')),
                ('assistant_notes', models.TextField(blank=True, verbose_name="ce que l'assistant doit savoir sur l'activité")),
                ('response_tone', models.CharField(choices=[('rassurant', 'Rassurant'), ('apaisant', 'Apaisant'), ('chaleureux', 'Chaleureux'), ('premium', 'Premium')], default='rassurant', max_length=20, verbose_name='manière de répondre')),
                ('public_assistant_enabled', models.BooleanField(default=False, verbose_name='assistant visible sur le profil public')),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to='professionals.professionalprofile')),
            ],
            options={
                'verbose_name': 'assistant praticien',
                'verbose_name_plural': 'assistants praticiens',
            },
        ),
    ]
