# Generated by Django 6.0.3 on 2026-03-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalassistantprofile',
            name='assistant_enabled',
            field=models.BooleanField(default=False, verbose_name='assistant activé'),
        ),
        migrations.AddField(
            model_name='professionalassistantprofile',
            name='avoid_topics',
            field=models.TextField(blank=True, verbose_name='questions à ne pas traiter'),
        ),
        migrations.AddField(
            model_name='professionalassistantprofile',
            name='business_rules',
            field=models.TextField(blank=True, verbose_name='règles métier'),
        ),
        migrations.AddField(
            model_name='professionalassistantprofile',
            name='general_guidance',
            field=models.TextField(blank=True, verbose_name='consignes de réponse'),
        ),
        migrations.AddField(
            model_name='professionalassistantprofile',
            name='guardrails',
            field=models.TextField(blank=True, verbose_name='garde-fous'),
        ),
        migrations.AddField(
            model_name='professionalassistantprofile',
            name='internal_context',
            field=models.TextField(blank=True, verbose_name='note interne de contexte'),
        ),
        migrations.AddField(
            model_name='professionalassistantprofile',
            name='welcome_message',
            field=models.CharField(blank=True, max_length=220, verbose_name="message d'accueil"),
        ),
        migrations.AlterField(
            model_name='professionalassistantprofile',
            name='response_tone',
            field=models.CharField(choices=[('rassurant', 'Rassurant'), ('apaisant', 'Apaisant'), ('chaleureux', 'Chaleureux'), ('professionnel', 'Professionnel'), ('premium', 'Haut de gamme'), ('sobre', 'Sobre')], default='rassurant', max_length=20, verbose_name='manière de répondre'),
        ),
    ]
