# Generated by Django 6.0.3 on 2026-03-25 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('session_key', models.CharField(blank=True, max_length=120, verbose_name='identifiant local')),
                ('consent_version', models.CharField(max_length=40, verbose_name='version CMP')),
                ('source', models.CharField(choices=[('banner', 'Bandeau'), ('preferences', 'Centre de préférences'), ('support', 'Support')], default='banner', max_length=20, verbose_name='source')),
                ('necessary', models.BooleanField(default=True, verbose_name='cookies nécessaires')),
                ('analytics', models.BooleanField(default=False, verbose_name="mesure d'audience")),
                ('advertising', models.BooleanField(default=False, verbose_name='publicité / retargeting')),
                ('support', models.BooleanField(default=False, verbose_name='support / tiers')),
                ('accepted_at', models.DateTimeField(verbose_name='consenti le')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='retiré le')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='empreinte IP')),
                ('user_agent_hash', models.CharField(blank=True, max_length=64, verbose_name='empreinte user agent')),
                ('evidence', models.JSONField(blank=True, default=dict, verbose_name='preuve complémentaire')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cookie_consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'preuve de consentement cookies',
                'verbose_name_plural': 'preuves de consentement cookies',
                'ordering': ('-accepted_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='LegalAcceptanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('email_snapshot', models.EmailField(blank=True, max_length=254, verbose_name="email au moment de l'acceptation")),
                ('document_slug', models.CharField(max_length=60, verbose_name='document')),
                ('document_version', models.CharField(max_length=40, verbose_name='version')),
                ('source', models.CharField(choices=[('registration', 'Inscription'), ('dashboard', 'Espace praticien'), ('booking', 'Réservation'), ('support', 'Support')], default='registration', max_length=20, verbose_name="contexte d'acceptation")),
                ('accepted_at', models.DateTimeField(verbose_name='accepté le')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='empreinte IP')),
                ('user_agent_hash', models.CharField(blank=True, max_length=64, verbose_name='empreinte user agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_acceptance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "preuve d'acceptation légale",
                'verbose_name_plural': "preuves d'acceptation légale",
                'ordering': ('-accepted_at', '-created_at'),
                'indexes': [models.Index(fields=['document_slug', 'document_version'], name='common_lega_documen_7d9b56_idx')],
            },
        ),
    ]
