# Generated by Django 6.0.3 on 2026-03-26 13:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('title', models.CharField(max_length=160, verbose_name='titre')),
                ('body', models.TextField(verbose_name='message')),
                ('audience_role', models.CharField(choices=[('all', 'Tous'), ('professional', 'Praticiens'), ('admin', 'Admins')], default='all', max_length=20, verbose_name='audience')),
                ('display_mode', models.CharField(choices=[('notice', 'Bandeau'), ('popup', 'Popup')], default='notice', max_length=20, verbose_name="mode d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='début')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'annonce admin',
                'verbose_name_plural': 'annonces admin',
                'ordering': ('-starts_at', '-created_at'),
                'indexes': [models.Index(fields=['audience_role', 'is_active'], name='common_admi_audienc_7587c1_idx'), models.Index(fields=['starts_at', 'ends_at'], name='common_admi_starts__2349d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlatformMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('category', models.CharField(choices=[('support', 'Support'), ('billing', 'Paiement'), ('moderation', 'Modération'), ('product', 'Produit'), ('system', 'Système')], default='support', max_length=20)),
                ('title', models.CharField(max_length=160, verbose_name='titre')),
                ('body', models.TextField(verbose_name='message')),
                ('display_mode', models.CharField(choices=[('inbox', 'Boîte de réception'), ('notice', 'Bandeau interne'), ('popup', "Popup à l'ouverture")], default='inbox', max_length=20, verbose_name="mode d'affichage")),
                ('reply_allowed', models.BooleanField(default=False, verbose_name='réponse autorisée')),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='envoyé le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_platform_messages', to=settings.AUTH_USER_MODEL)),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message plateforme',
                'verbose_name_plural': 'messages plateforme',
                'ordering': ('-sent_at', '-created_at'),
                'permissions': [('manage_support_messages', 'Can manage support messages'), ('view_admin_analytics', 'Can view admin analytics')],
                'indexes': [models.Index(fields=['recipient_user', 'is_read', 'is_active'], name='common_plat_recipie_507133_idx'), models.Index(fields=['display_mode', 'is_active'], name='common_plat_display_2973fd_idx')],
            },
        ),
    ]
