# Generated by Django 6.0.3 on 2026-03-28 00:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_adminannouncement_platformmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformmessage',
            options={'ordering': ('-sent_at', '-created_at'), 'permissions': [('manage_support_messages', 'Can manage support messages'), ('view_admin_analytics', 'Can view admin analytics'), ('manage_admin_users', 'Can manage admin users'), ('manage_admin_campaigns', 'Can manage admin campaigns'), ('view_admin_ranking', 'Can view admin ranking'), ('manage_platform_settings', 'Can manage platform settings')], 'verbose_name': 'message plateforme', 'verbose_name_plural': 'messages plateforme'},
        ),
        migrations.CreateModel(
            name='PageViewEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('path', models.CharField(max_length=255, verbose_name='chemin')),
                ('page_group', models.CharField(blank=True, max_length=80, verbose_name='groupe')),
                ('city_slug', models.SlugField(blank=True, max_length=170, verbose_name='ville')),
                ('referrer', models.CharField(blank=True, max_length=255, verbose_name='referrer')),
                ('session_key', models.CharField(blank=True, max_length=120, verbose_name='session locale')),
                ('visitor_type', models.CharField(choices=[('anonymous', 'Visiteur'), ('professional', 'Praticien'), ('admin', 'Admin')], default='anonymous', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='vu le')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_view_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'événement de vue',
                'verbose_name_plural': 'événements de vue',
                'ordering': ('-occurred_at', '-created_at'),
                'indexes': [models.Index(fields=['occurred_at'], name='common_page_occurre_1ddf58_idx'), models.Index(fields=['path'], name='common_page_path_2e7455_idx'), models.Index(fields=['page_group'], name='common_page_page_gr_c9e466_idx'), models.Index(fields=['city_slug'], name='common_page_city_sl_463c8b_idx'), models.Index(fields=['visitor_type'], name='common_page_visitor_07cd33_idx')],
            },
        ),
    ]
